blizzard-api:
  urls:
    base-url: http://localhost:3000/

spring:
  application:
    name: azeroth-intel-data-api
  cache:
    jcache:
      config: classpath:ehcache.xml
      provider: org.ehcache.jsr107.EhcacheCachingProvider
    type: jcache
  datasource:
    url: jdbc:postgresql://localhost:5432/azeroth_intel_db
    username: azeroth_data_writer_user
    password: w1+LTlM6£E^&gIz2X!G5Cg6L%u<Ys}ep!
  jpa:
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 500
        order_updates: true
        order_inserts: true
        batch_versioned_data: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: false
    default-schema: public
  reactor:
    context-propagation: auto

server:
  port: 8081

springdoc:
  show-actuator: true

